name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make vendor openssl and cryptoccp
      run: make vendor
      
    - name: make test
      run: make test
